In [34]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plot
chi_df = pd.read_csv("chicago_demo.csv",
                         keep_default_na=False, na_values=[""])
chi_df

,lab_report_date,cases_total,deaths_total,cases_age_0_17,cases_age_18_29,cases_age_30_39,cases_age_40_49,cases_age_50_59,cases_age_60_69,cases_age_70_79,...,deaths_unknown_age,deaths_female,deaths_male,deaths_unknown_gender,deaths_latinx,deaths_asian_non_latinx,deaths_black_non_latinx,deaths_white_non_latinx,deaths_other_non_latinx,deaths_unknown_race_eth
0,7/17/2020,1,1,0,1,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,1
1,7/16/2020,39,0,1,17,7,6,2,2,1,...,0,0,0,0,0,0,0,0,0,0
2,7/15/2020,98,4,15,22,18,12,11,9,7,...,0,1,3,0,1,0,3,0,0,0
3,7/14/2020,234,3,36,60,39,36,30,18,13,...,0,3,0,0,1,0,0,0,0,2
4,7/13/2020,255,4,26,74,52,36,27,24,4,...,0,1,3,0,2,0,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
132,3/7/2020,3,0,0,0,0,0,1,0,2,...,0,0,0,0,0,0,0,0,0,0
133,3/6/2020,3,0,0,0,0,2,0,1,0,...,0,0,0,0,0,0,0,0,0,0
134,3/5/2020,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
135,2/28/2020,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
136,1/21/2020,1,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0

In [35]:
chicase_by_race_df = chi_df[["lab_report_date",
                      "cases_total",
                      "cases_latinx",
                      "cases_asian_non_latinx",
                      "cases_black_non_latinx",
                      "cases_white_non_latinx",
                      "cases_other_non_latinx",
                     "cases_unknown_race_eth"]]

# Clean the data by dropping empty row
chicase_by_race_df = chicase_by_race_df.dropna(how = "any")

# Change data type from str to int
cols = chicase_by_race_df.columns.drop("lab_report_date")
chicase_by_race_df[cols] = chicase_by_race_df[cols].apply(pd.to_numeric, errors='coerce')

# Remove time from date&time variable
chicase_by_race_df["lab_report_date"] = pd.to_datetime(chicase_by_race_df["lab_report_date"]).dt.date

In [36]:
il_df = pd.read_csv("ILCovid.csv",
                         keep_default_na=False, na_values=[""])
il_df

,Date,State,Cases_Total,Cases_White,Cases_Black,Cases_LatinX,Cases_Asian,Cases_AIAN,Cases_NHPI,Cases_Other,...,Deaths_Black,Deaths_LatinX,Deaths_Asian,Deaths_AIAN,Deaths_NHPI,Deaths_Other,Deaths_Unknown,Deaths_Ethnicity_Hispanic,Deaths_Ethnicity_NonHispanic,Deaths_Ethnicity_Unknown
0,7/15/2020,IL,157825,34463,26330,49483,4373,228,390,5827,...,1998,1491,346,10,8,52,303,1491,5633,102
1,7/12/2020,IL,155048,33468,25828,48999,4317,226,385,5719,...,1990,1482,343,10,8,52,304,1482,5602,103
2,7/8/2020,IL,150554,31974,25072,48116,4249,225,384,5544,...,1967,1460,337,10,8,51,313,1460,5536,103
3,7/5/2020,IL,148373,31143,24691,47679,4209,224,379,5493,...,1958,1448,329,10,7,48,307,1448,5475,97
4,7/1/2020,IL,144013,30175,24191,46832,4163,219,373,5383,...,1934,1435,327,9,7,48,101,1435,5415,101
5,6/28/2020,IL,141723,29505,23774,46213,4119,214,366,5361,...,1923,1417,325,9,6,49,98,1417,5373,98
6,6/24/2020,IL,138540,28469,23223,45294,4055,210,356,5263,...,1892,1383,322,9,6,50,50,1383,5283,104
7,6/21/2020,IL,136762,27901,22941,44647,3995,211,352,5218,...,1869,1353,318,9,6,51,51,1353,5196,98
8,6/17/2020,IL,134185,26830,22296,43765,3872,204,339,4798,...,1832,1301,306,9,5,45,45,1301,5053,131
9,6/14/2020,IL,132543,26338,22004,42950,3803,201,331,4780,...,1793,1257,298,9,5,44,44,1257,4919,132
10,6/10/2020,IL,129837,25574,21575,41721,3716,202,325,4674,...,1746,1204,285,9,5,41,41,1204,4762,129
11,6/7/2020,IL,127757,25020,21192,40854,3663,197,320,4623,...,1704,1168,279,9,5,41,41,1168,4611,125
12,6/3/2020,IL,123830,24128,20506,39339,3556,193,301,4496,...,1646,1094,266,8,5,42,42,1094,4408,119
13,5/31/2020,IL,120260,23426,19939,37707,3465,191,294,4420,...,1588,1050,257,8,4,39,39,1050,4220,120
14,5/27/2020,IL,114306,22289,19135,35369,3319,182,282,4179,...,1517,984,247,7,4,36,36,984,3977,122
15,5/24/2020,IL,110304,21659,18605,34106,3234,181,278,4037,...,1469,923,236,7,3,36,36,923,3821,112
16,5/20/2020,IL,100418,20251,17512,30555,3003,173,261,3801,...,1394,828,215,9,3,38,38,828,3587,110
17,5/17/2020,IL,94191,19218,16616,27763,2830,159,219,3643,...,1316,747,194,7,2,31,31,747,3335,95
18,5/13/2020,IL,84698,17407,15034,23259,2529,138,164,3390,...,1217,643,169,7,2,36,36,643,3042,107
19,5/10/2020,IL,77741,16390,14369,20839,2408,126,123,3142,...,1106,554,147,6,2,27,27,554,2738,114
20,5/6/2020,IL,68232,14809,13277,17240,2203,99,73,2766,...,998,457,124,5,3,25,25,457,2417,100
21,5/3/2020,IL,61499,13566,12240,14502,2001,82,67,2524,...,904,379,111,3,3,30,30,379,2147,92
22,4/29/2020,IL,50355,11676,10850,10846,1718,70,62,2031,...,796,297,91,2,2,24,24,297,1827,91
23,4/26/2020,IL,43903,10427,9918,8743,1523,65,52,1834,...,712,245,76,2,2,19,19,245,1605,83
24,4/22/2020,IL,35108,8573,8504,6195,1244,50,45,1447,...,596,181,62,1,3,21,21,181,1304,80
25,4/19/2020,IL,30357,7554,7498,4913,1085,46,39,1324,...,502,134,51,512,2,15,15,134,1583,74

In [37]:
# Case by race dataframe
case_by_race_df = il_df[["Date",
                      "Cases_Total",
                      "Cases_LatinX",
                      "Cases_Asian",
                      "Cases_Black",
                      "Cases_White",
                      "Cases_AIAN",
                      "Cases_NHPI",
                       "Cases_Other"]]

# Clean the data by dropping empty row
case_by_race_df = case_by_race_df.dropna(how = "any")

# Change data type from str to int
cols = case_by_race_df.columns.drop("Date")
case_by_race_df[cols] = case_by_race_df[cols].apply(pd.to_numeric, errors='coerce')

# Remove time from date&time variable
case_by_race_df["Date"] = pd.to_datetime(case_by_race_df["Date"]).dt.date

ValueError: Could not interpret input 'x'