In [7]:
import pandas as pd

il_pop = pd.read_csv('csv_files/Illinois_demographics.csv')

il_pop.head(50)

,ID Race,Race,ID Ethnicity,Ethnicity,ID Year,Year,Hispanic Population Moe,Geography,ID Geography,Slug Geography,Population,share
0,1,Black or African American Alone,0,Not Hispanic or Latino,2018,2018,8262.000000,Illinois,04000US17,illinois,1759316,0.138082
1,6,Two or More Races,1,Hispanic or Latino,2018,2018,7126.599470,Illinois,04000US17,illinois,85195,0.006687
2,0,White Alone,0,Not Hispanic or Latino,2018,2018,3669.000000,Illinois,04000US17,illinois,7760732,0.609111
3,5,Some Other Race Alone,1,Hispanic or Latino,2018,2018,25315.000000,Illinois,04000US17,illinois,688468,0.054035
4,0,White Alone,1,Hispanic or Latino,2018,2018,26609.000000,Illinois,04000US17,illinois,1374413,0.107873
5,5,Some Other Race Alone,0,Not Hispanic or Latino,2018,2018,3879.000000,Illinois,04000US17,illinois,24310,0.001908
6,4,Native Hawaiian & Other Pacific Islander Alone,1,Hispanic or Latino,2018,2018,1638.000000,Illinois,04000US17,illinois,2430,0.000191
7,6,Two or More Races,0,Not Hispanic or Latino,2018,2018,10539.268480,Illinois,04000US17,illinois,255782,0.020075
8,4,Native Hawaiian & Other Pacific Islander Alone,0,Not Hispanic or Latino,2018,2018,697.000000,Illinois,04000US17,illinois,2887,0.000227
9,1,Black or African American Alone,1,Hispanic or Latino,2018,2018,5076.000000,Illinois,04000US17,illinois,33763,0.002650
10,3,Asian Alone,1,Hispanic or Latino,2018,2018,1829.000000,Illinois,04000US17,illinois,5968,0.000468
11,3,Asian Alone,0,Not Hispanic or Latino,2018,2018,6521.000000,Illinois,04000US17,illinois,711970,0.055880
12,2,American Indian & Alaska Native Alone,0,Not Hispanic or Latino,2018,2018,2351.000000,Illinois,04000US17,illinois,17215,0.001351
13,2,American Indian & Alaska Native Alone,1,Hispanic or Latino,2018,2018,4332.000000,Illinois,04000US17,illinois,18631,0.001462
14,5,Some Other Race Alone,1,Hispanic or Latino,2017,2017,25961.000000,Illinois,04000US17,illinois,777941,0.060767
15,4,Native Hawaiian & Other Pacific Islander Alone,1,Hispanic or Latino,2017,2017,541.000000,Illinois,04000US17,illinois,1038,0.000081
16,0,White Alone,1,Hispanic or Latino,2017,2017,26683.000000,Illinois,04000US17,illinois,1285640,0.100425
17,4,Native Hawaiian & Other Pacific Islander Alone,0,Not Hispanic or Latino,2017,2017,1787.000000,Illinois,04000US17,illinois,3822,0.000299
18,1,Black or African American Alone,1,Hispanic or Latino,2017,2017,4150.000000,Illinois,04000US17,illinois,28474,0.002224
19,6,Two or More Races,1,Hispanic or Latino,2017,2017,8784.531974,Illinois,04000US17,illinois,91441,0.007143
20,6,Two or More Races,0,Not Hispanic or Latino,2017,2017,11154.255870,Illinois,04000US17,illinois,244030,0.019062
21,3,Asian Alone,1,Hispanic or Latino,2017,2017,1251.000000,Illinois,04000US17,illinois,5267,0.000411
22,5,Some Other Race Alone,0,Not Hispanic or Latino,2017,2017,4106.000000,Illinois,04000US17,illinois,19975,0.001560
23,2,American Indian & Alaska Native Alone,0,Not Hispanic or Latino,2017,2017,1786.000000,Illinois,04000US17,illinois,12784,0.000999
24,0,White Alone,0,Not Hispanic or Latino,2017,2017,4560.000000,Illinois,04000US17,illinois,7834272,0.611956
25,3,Asian Alone,0,Not Hispanic or Latino,2017,2017,6059.000000,Illinois,04000US17,illinois,689701,0.053874
26,1,Black or African American Alone,0,Not Hispanic or Latino,2017,2017,9362.000000,Illinois,04000US17,illinois,1790512,0.139862
27,2,American Indian & Alaska Native Alone,1,Hispanic or Latino,2017,2017,4400.000000,Illinois,04000US17,illinois,17126,0.001338
28,2,American Indian & Alaska Native Alone,1,Hispanic or Latino,2016,2016,3358.000000,Illinois,04000US17,illinois,15055,0.001176
29,6,Two or More Races,1,Hispanic or Latino,2016,2016,7611.711503,Illinois,04000US17,illinois,92358,0.007215
30,3,Asian Alone,0,Not Hispanic or Latino,2016,2016,5814.000000,Illinois,04000US17,illinois,679106,0.053049
31,2,American Indian & Alaska Native Alone,0,Not Hispanic or Latino,2016,2016,2212.000000,Illinois,04000US17,illinois,15415,0.001204
32,0,White Alone,0,Not Hispanic or Latino,2016,2016,3458.000000,Illinois,04000US17,illinois,7886677,0.616073
33,6,Two or More Races,0,Not Hispanic or Latino,2016,2016,11314.559160,Illinois,04000US17,illinois,229053,0.017893
34,3,Asian Alone,1,Hispanic or Latino,2016,2016,1556.000000,Illinois,04000US17,illinois,5677,0.000443
35,0,White Alone,1,Hispanic or Latino,2016,2016,25149.000000,Illinois,04000US17,illinois,1237086,0.096636
36,5,Some Other Race Alone,1,Hispanic or Latino,2016,2016,25148.000000,Illinois,04000US17,illinois,804066,0.062810
37,4,Native Hawaiian & Other Pacific Islander Alone,0,Not Hispanic or Latino,2016,2016,1193.000000,Illinois,04000US17,illinois,3126,0.000244
38,1,Black or African American Alone,1,Hispanic or Latino,2016,2016,3326.000000,Illinois,04000US17,illinois,22823,0.001783
39,5,Some Other Race Alone,0,Not Hispanic or Latino,2016,2016,3487.000000,Illinois,04000US17,illinois,18718,0.001462
40,1,Black or African American Alone,0,Not Hispanic or Latino,2016,2016,8660.000000,Illinois,04000US17,illinois,1790654,0.139878
41,4,Native Hawaiian & Other Pacific Islander Alone,1,Hispanic or Latino,2016,2016,665.000000,Illinois,04000US17,illinois,1725,0.000135
42,2,American Indian & Alaska Native Alone,0,Not Hispanic or Latino,2015,2015,2238.000000,Illinois,04000US17,illinois,13082,0.001017
43,3,Asian Alone,0,Not Hispanic or Latino,2015,2015,6380.000000,Illinois,04000US17,illinois,669595,0.052068
44,5,Some Other Race Alone,0,Not Hispanic or Latino,2015,2015,3176.000000,Illinois,04000US17,illinois,17864,0.001389
45,1,Black or African American Alone,1,Hispanic or Latino,2015,2015,4591.000000,Illinois,04000US17,illinois,31177,0.002424
46,1,Black or African American Alone,0,Not Hispanic or Latino,2015,2015,7672.000000,Illinois,04000US17,illinois,1813447,0.141015
47,5,Some Other Race Alone,1,Hispanic or Latino,2015,2015,23535.000000,Illinois,04000US17,illinois,755821,0.058773
48,4,Native Hawaiian & Other Pacific Islander Alone,0,Not Hispanic or Latino,2015,2015,996.000000,Illinois,04000US17,illinois,3191,0.000248
49,4,Native Hawaiian & Other Pacific Islander Alone,1,Hispanic or Latino,2015,2015,831.000000,Illinois,04000US17,illinois,1323,0.000103

In [8]:
# look at shape
il_pop.shape

(84, 12)

In [60]:
il_pop.columns = map(str.lower, il_pop.columns)
il_pop.columns = ['id_race', 'race', 'id_eth', 'ethnicity', 'id_year', 'year',
       'hispanic_pop', 'geography', 'id_geography',
       'slug_geography', 'il_population_2018', 'share']
il_pop

,id_race,race,id_eth,ethnicity,id_year,year,hispanic_pop,geography,id_geography,slug_geography,il_population_2018,share
0,1,Black or African American Alone,0,Not Hispanic or Latino,2018,2018,8262.00000,Illinois,04000US17,illinois,1759316,0.138082
1,6,Two or More Races,1,Hispanic or Latino,2018,2018,7126.59947,Illinois,04000US17,illinois,85195,0.006687
2,0,White Alone,0,Not Hispanic or Latino,2018,2018,3669.00000,Illinois,04000US17,illinois,7760732,0.609111
3,5,Some Other Race Alone,1,Hispanic or Latino,2018,2018,25315.00000,Illinois,04000US17,illinois,688468,0.054035
4,0,White Alone,1,Hispanic or Latino,2018,2018,26609.00000,Illinois,04000US17,illinois,1374413,0.107873
...,...,...,...,...,...,...,...,...,...,...,...,...
79,5,Some Other Race Alone,1,Hispanic or Latino,2013,2013,20731.00000,Illinois,04000US17,illinois,713096,0.055355
80,1,Black or African American Alone,1,Hispanic or Latino,2013,2013,4464.00000,Illinois,04000US17,illinois,26671,0.002070
81,4,Native Hawaiian & Other Pacific Islander Alone,0,Not Hispanic or Latino,2013,2013,850.00000,Illinois,04000US17,illinois,2911,0.000226
82,1,Black or African American Alone,0,Not Hispanic or Latino,2013,2013,7871.00000,Illinois,04000US17,illinois,1806889,0.140263
83,3,Asian Alone,1,Hispanic or Latino,2013,2013,1290.00000,Illinois,04000US17,illinois,4171,0.000324

In [61]:
# create new df for just 2018 data
il_pop_2018 = il_pop.loc[il_pop["id_year"] == 2018, :]
il_pop_2018

,id_race,race,id_eth,ethnicity,id_year,year,hispanic_pop,geography,id_geography,slug_geography,il_population_2018,share
0,1,Black or African American Alone,0,Not Hispanic or Latino,2018,2018,8262.00000,Illinois,04000US17,illinois,1759316,0.138082
1,6,Two or More Races,1,Hispanic or Latino,2018,2018,7126.59947,Illinois,04000US17,illinois,85195,0.006687
2,0,White Alone,0,Not Hispanic or Latino,2018,2018,3669.00000,Illinois,04000US17,illinois,7760732,0.609111
3,5,Some Other Race Alone,1,Hispanic or Latino,2018,2018,25315.00000,Illinois,04000US17,illinois,688468,0.054035
4,0,White Alone,1,Hispanic or Latino,2018,2018,26609.00000,Illinois,04000US17,illinois,1374413,0.107873
5,5,Some Other Race Alone,0,Not Hispanic or Latino,2018,2018,3879.00000,Illinois,04000US17,illinois,24310,0.001908
6,4,Native Hawaiian & Other Pacific Islander Alone,1,Hispanic or Latino,2018,2018,1638.00000,Illinois,04000US17,illinois,2430,0.000191
7,6,Two or More Races,0,Not Hispanic or Latino,2018,2018,10539.26848,Illinois,04000US17,illinois,255782,0.020075
8,4,Native Hawaiian & Other Pacific Islander Alone,0,Not Hispanic or Latino,2018,2018,697.00000,Illinois,04000US17,illinois,2887,0.000227
9,1,Black or African American Alone,1,Hispanic or Latino,2018,2018,5076.00000,Illinois,04000US17,illinois,33763,0.002650
10,3,Asian Alone,1,Hispanic or Latino,2018,2018,1829.00000,Illinois,04000US17,illinois,5968,0.000468
11,3,Asian Alone,0,Not Hispanic or Latino,2018,2018,6521.00000,Illinois,04000US17,illinois,711970,0.055880
12,2,American Indian & Alaska Native Alone,0,Not Hispanic or Latino,2018,2018,2351.00000,Illinois,04000US17,illinois,17215,0.001351
13,2,American Indian & Alaska Native Alone,1,Hispanic or Latino,2018,2018,4332.00000,Illinois,04000US17,illinois,18631,0.001462

In [62]:

il_pop_2018 = il_pop.loc[il_pop['id_year'] == 2018,["race","ethnicity","il_population_2018","share"]]
il_pop_2018 ["race/ethnicity"] = ["black","latinx","white","latinx","latinx","other","latinx","other","other","latinx","latinx","asian","other","latinx"]
il_pop_2018

,race,ethnicity,il_population_2018,share,race/ethnicity
0,Black or African American Alone,Not Hispanic or Latino,1759316,0.138082,black
1,Two or More Races,Hispanic or Latino,85195,0.006687,latinx
2,White Alone,Not Hispanic or Latino,7760732,0.609111,white
3,Some Other Race Alone,Hispanic or Latino,688468,0.054035,latinx
4,White Alone,Hispanic or Latino,1374413,0.107873,latinx
5,Some Other Race Alone,Not Hispanic or Latino,24310,0.001908,other
6,Native Hawaiian & Other Pacific Islander Alone,Hispanic or Latino,2430,0.000191,latinx
7,Two or More Races,Not Hispanic or Latino,255782,0.020075,other
8,Native Hawaiian & Other Pacific Islander Alone,Not Hispanic or Latino,2887,0.000227,other
9,Black or African American Alone,Hispanic or Latino,33763,0.002650,latinx
10,Asian Alone,Hispanic or Latino,5968,0.000468,latinx
11,Asian Alone,Not Hispanic or Latino,711970,0.055880,asian
12,American Indian & Alaska Native Alone,Not Hispanic or Latino,17215,0.001351,other
13,American Indian & Alaska Native Alone,Hispanic or Latino,18631,0.001462,latinx

In [63]:
il_race = il_pop_2018.groupby('race/ethnicity')
race_count_il = pd.DataFrame(il_race['il_population_2018'].sum())
race_count_il

                il_population_2018
race/ethnicity
asian                       711970
black                      1759316
latinx                     2208868
other                       300194
white                      7760732

In [66]:
il_ethnicity = il_pop_2018.groupby('ethnicity')
ethnicity_count_il = pd.DataFrame(il_ethnicity['il_population_2018'].sum())
ethnicity_count_il

                        il_population_2018
ethnicity
Hispanic or Latino                 2208868
Not Hispanic or Latino            10532212

In [67]:
race_count_il.to_csv("csv_files/il_race_count.csv")